const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ru-RU').format(Number(n)||0)+' so‘m';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lang=localStorage.getItem('lang')||'uz', products=[], categories=[], settings={}, logo='', filter='all', search='', sort='featured';
let cart=JSON.parse(localStorage.getItem('iob_cart_v13')||'[]'), favorites=JSON.parse(localStorage.getItem('iob_favs_v13')||'[]'), qtyPick={}, promo={code:'',discount:0};
const T={uz:{home:'Bosh sahifa',products:'Mahsulotlar',about:'Biz haqimizda',contact:'Aloqa',add:'Savatga',out:'Tugagan',stock:'Omborda',fav:'Sevimlilar',track:'Buyurtmani kuzatish'},ru:{home:'Главная',products:'Товары',about:'О нас',contact:'Контакты',add:'В корзину',out:'Нет в наличии',stock:'В наличии',fav:'Избранное',track:'Отследить заказ'},en:{home:'Home',products:'Products',about:'About',contact:'Contact',add:'Add to cart',out:'Out of stock',stock:'In stock',fav:'Favorites',track:'Track order'}};

function saveCart(){localStorage.setItem('iob_cart_v13',JSON.stringify(cart));}
function saveFavs(){localStorage.setItem('iob_favs_v13',JSON.stringify(favorites));}
function nameOf(p){return p?.name?.[lang]||p?.name?.uz||''}
function categoryById(id){return categories.find(c=>c.id===id)||{id:'x',icon:'🛍️',name:{uz:'Boshqa',ru:'Другое',en:'Other'}}}
function cartQty(id){return Number(cart.find(x=>Number(x.id)===Number(id))?.qty||0)}
function subtotal(){return cart.reduce((s,x)=>{const p=products.find(p=>Number(p.id)===Number(x.id));return s+(p?Number(p.price||0)*Number(x.qty||0):0)},0)}
function total(){return Math.max(0,subtotal()-Number(promo.discount||0))}

async function loadCatalog(){try{const r=await fetch('/api/catalog',{cache:'no-store'});const d=await r.json();products=d.products||[];categories=d.categories||[];settings=d.settings||{};logo=d.logo||'';applySite();renderAll();}catch(e){console.error(e)}}
function applySite(){document.body.dataset.theme=settings.theme||'original';const L=x=>x?.[lang]||x?.uz||x||'';$('#language').value=lang;$$('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(T[lang]?.[k])el.textContent=T[lang][k]});$('#topDomain').textContent=settings.siteDomain||'velora.uz';$('#brandDomain').textContent=(settings.siteDomain||'velora.uz').toUpperCase();$('#heroDomain')&&($('#heroDomain').textContent=settings.siteDomain||'velora.uz');$('#footerDomain').textContent=settings.siteDomain||'velora.uz';$('#brandName').textContent=settings.siteName||'IMOM OTA BARAKA';$('#footerName').textContent=settings.siteName||'IMOM OTA BARAKA';$('#tagline').textContent=L(settings.tagline)||'Sifat, ishonch, baraka!';$('#footerTagline').textContent=L(settings.tagline)||'';$('#heroEyebrow')&&($('#heroEyebrow').textContent=L(settings.hero)?.eyebrow||settings.hero?.[lang]?.eyebrow||settings.hero?.uz?.eyebrow||'');$('#heroTitle')&&($('#heroTitle').textContent=settings.hero?.[lang]?.title||settings.hero?.uz?.title||'');$('#heroText')&&($('#heroText').textContent=settings.hero?.[lang]?.text||settings.hero?.uz?.text||'');$('#aboutTitle').textContent=settings.about?.[lang]?.title||settings.about?.uz?.title||'';$('#aboutText').textContent=settings.about?.[lang]?.text||settings.about?.uz?.text||'';$('#contactTitle').textContent=settings.contact?.[lang]?.title||settings.contact?.uz?.title||'';$('#contactText').textContent=settings.contact?.[lang]?.text||settings.contact?.uz?.text||'';const phone=settings.phone||'+998901361211',tg=settings.telegram||'https://t.me/imomotabaraka',email=settings.email||'info@imomotamarket.uz';['#topPhone','#contactPhone','#contactPhoneBtn'].forEach(s=>{$(s).href='tel:'+phone;});$('#topPhone').textContent=formatPhone(phone);$('#contactPhone').textContent=formatPhone(phone);['#topTelegram','#contactTelegram','#contactTelegramBtn','#floatingTelegram'].forEach(s=>{$(s).href=tg});$('#contactEmail').href='mailto:'+email;$('#contactEmail').textContent=email;if(logo){$$('.sphere-logo img').forEach(i=>i.src=logo)}
 document.title=settings.seo?.title||`${settings.siteName||'IMOM OTA BARAKA'} — ${settings.siteDomain||'velora.uz'}`;document.querySelector('meta[name=description]')?.setAttribute('content',settings.seo?.description||'');}
function formatPhone(p){const d=String(p).replace(/\D/g,'');if(d.length===12)return `+${d.slice(0,3)} ${d.slice(3,5)} ${d.slice(5,8)} ${d.slice(8,10)} ${d.slice(10)}`;return p}
function renderAll(){renderCategories();renderProducts();renderCart();renderFavCount();}
function renderCategories(){const all=`<button class="category-pill ${filter==='all'?'active':''}" onclick="setFilter('all')"><b>Barchasi</b></button>`;const xs=categories.map(c=>`<button class="category-pill ${filter===c.id?'active':''}" onclick="setFilter('${esc(c.id)}')"><b>${esc(c.name?.[lang]||c.name?.uz||'')}</b></button>`).join('');$('#categoryStrip').innerHTML=all+xs;$('#categoryFilters').innerHTML=`<button class="filter ${filter==='all'?'active':''}" onclick="setFilter('all')">Barchasi</button>`+categories.map(c=>`<button class="filter ${filter===c.id?'active':''}" onclick="setFilter('${esc(c.id)}')">${esc(c.name?.[lang]||c.name?.uz||'')}</button>`).join('')}
function setFilter(v){filter=v;renderCategories();renderProducts();document.querySelector('#products').scrollIntoView({behavior:'smooth'});}
function productList(){let arr=products.filter(p=>(filter==='all'||p.cat===filter)&&(!search||nameOf(p).toLowerCase().includes(search.toLowerCase())||String(p.badge||'').toLowerCase().includes(search.toLowerCase())));if(sort==='priceAsc')arr.sort((a,b)=>a.price-b.price);else if(sort==='priceDesc')arr.sort((a,b)=>b.price-a.price);else if(sort==='new')arr.sort((a,b)=>Number(b.id)-Number(a.id));else arr.sort((a,b)=>Number(b.featured)-Number(a.featured));return arr}
function renderProducts(){const arr=productList();$('#productGrid').innerHTML=arr.length?arr.map(p=>{const q=qtyPick[p.id]||1,c=categoryById(p.cat),fav=favorites.includes(Number(p.id)),stock=Number(p.stock||0);return `<article class="product-card"><button class="fav-btn ${fav?'on':''}" onclick="toggleFav(${p.id})">${fav?'♥':'♡'}</button>${p.badge?`<span class="badge">${esc(p.badge)}</span>`:''}<div class="product-media">${p.image?`<img src="${p.image}" alt="${esc(nameOf(p))}">`:`<span class="no-image">Rasm yo‘q</span>`}</div><div class="product-body"><small>${esc(c.name?.[lang]||c.name?.uz||'')}</small><h3>${esc(nameOf(p))}</h3><div class="price-row"><div>${p.oldPrice>p.price?`<del>${money(p.oldPrice)}</del>`:''}<b>${money(p.price)}</b></div><span>${T[lang].stock}: ${stock}</span></div><div class="qty-add"><div class="stepper"><button onclick="pickQty(${p.id},-1)">−</button><b id="pick-${p.id}">${q}</b><button onclick="pickQty(${p.id},1)">+</button></div><button class="add-btn" ${stock<=0?'disabled':''} onclick="addToCart(${p.id})">${stock<=0?T[lang].out:T[lang].add}</button></div></div></article>`}).join(''):`<div class="empty-state"><h3>Mahsulot topilmadi</h3><p>Qidiruv yoki filtrni o‘zgartiring.</p></div>`}
function pickQty(id,d){const p=products.find(x=>Number(x.id)===Number(id));let q=Number(qtyPick[id]||1)+d;q=Math.max(1,Math.min(Number(p?.stock||1),q));qtyPick[id]=q;const el=document.getElementById('pick-'+id);if(el)el.textContent=q}
function addToCart(id){const p=products.find(x=>Number(x.id)===Number(id));if(!p)return;const add=Number(qtyPick[id]||1),found=cart.find(x=>Number(x.id)===Number(id)),next=(found?.qty||0)+add;if(next>Number(p.stock||0)){alert('Omborda yetarli mahsulot yo‘q.');return}if(found)found.qty=next;else cart.push({id:Number(id),qty:add});qtyPick[id]=1;promo.discount=0;saveCart();renderCart();openCart();renderProducts()}
function changeCart(id,d){const x=cart.find(x=>Number(x.id)===Number(id)),p=products.find(p=>Number(p.id)===Number(id));if(!x||!p)return;const q=x.qty+d;if(q<=0)cart=cart.filter(a=>Number(a.id)!==Number(id));else if(q<=Number(p.stock||0))x.qty=q;promo.discount=0;saveCart();renderCart();renderProducts()}
function removeCart(id){cart=cart.filter(a=>Number(a.id)!==Number(id));promo.discount=0;saveCart();renderCart();renderProducts()}
function renderCart(){const valid=cart.filter(x=>products.some(p=>Number(p.id)===Number(x.id)));cart=valid;saveCart();const count=cart.reduce((s,x)=>s+Number(x.qty||0),0);$('#cartCount').textContent=count;$('#cartSub').textContent=`${count} ta mahsulot`;$('#cartItems').innerHTML=cart.length?cart.map(x=>{const p=products.find(p=>Number(p.id)===Number(x.id));return `<div class="cart-line"><div class="cart-thumb">${p.image?`<img src="${p.image}">`:'Rasm yo‘q'}</div><div class="cart-info"><b>${esc(nameOf(p))}</b><span>${money(p.price)} × ${x.qty}</span><div class="mini-stepper"><button onclick="changeCart(${p.id},-1)">−</button><b>${x.qty}</b><button onclick="changeCart(${p.id},1)">+</button></div></div><div class="cart-price"><b>${money(p.price*x.qty)}</b><button onclick="removeCart(${p.id})">×</button></div></div>`}).join(''):`<div class="empty-cart"><b>Savat bo‘sh</b><span>Mahsulotlarni tanlab savatga qo‘shing.</span></div>`;$('#cartSubtotal').textContent=money(subtotal());$('#cartDiscount').textContent='− '+money(promo.discount);$('#cartTotal').textContent=money(total());$('#mobileCartText').textContent=`Savat • ${money(total())}`;$('#mobileStickyCart').classList.toggle('show',count>0)}
function openCart(){$('#cartPanel').classList.add('open');$('#overlay').classList.add('show')}
function closeCart(){$('#cartPanel').classList.remove('open');$('#overlay').classList.remove('show')}
async function applyPromo(){const code=$('#cartPromo').value.trim();if(!code){promo={code:'',discount:0};renderCart();return}try{const r=await fetch('/api/promo/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,subtotal:subtotal()})});const d=await r.json();if(!r.ok)throw new Error(d.error);promo={code:d.code,discount:d.discount};renderCart();alert(`Promo kod qabul qilindi: -${money(d.discount)}`)}catch(e){promo={code:'',discount:0};renderCart();alert(e.message)}}
function toggleFav(id){id=Number(id);favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];saveFavs();renderFavCount();renderProducts()}
function renderFavCount(){$('#favCount').textContent=favorites.length}
function showFavorites(){if(!favorites.length){showModal(`<div class="modal-card"><button class="x" onclick="closeModal()">×</button><h2>♡ Sevimlilar</h2><p>Hali mahsulot saqlanmagan.</p></div>`);return}showModal(`<div class="modal-card wide"><button class="x" onclick="closeModal()">×</button><h2>♥ Sevimlilar</h2><div class="fav-list">${favorites.map(id=>{const p=products.find(x=>Number(x.id)===id);return p?`<div><span><b>${esc(nameOf(p))}</b></span><b>${money(p.price)}</b><button onclick="addToCart(${p.id});closeModal()">Savatga</button></div>`:''}).join('')}</div></div>`)}
function showModal(html){$('#modal').innerHTML=html;$('#modal').classList.add('show')}
function closeModal(){$('#modal').classList.remove('show')}
function openTracking(){showModal(`<div class="modal-card"><button class="x" onclick="closeModal()">×</button><span class="eyebrow">BUYURTMA KUZATUVI</span><h2>Buyurtma holatini tekshiring</h2><form class="track-form" onsubmit="trackOrder(event)"><input name="id" placeholder="IOB-12345678-10" required><input name="phone" placeholder="+998 90 123 45 67" required><button class="btn primary">Tekshirish</button></form><div id="trackResult"></div></div>`)}
async function trackOrder(e){e.preventDefault();const fd=new FormData(e.currentTarget),box=$('#trackResult');box.innerHTML='<p>Tekshirilmoqda...</p>';try{const r=await fetch(`/api/track/${encodeURIComponent(fd.get('id').trim())}?phone=${encodeURIComponent(fd.get('phone').trim())}`);const d=await r.json();if(!r.ok)throw new Error(d.error);box.innerHTML=`<div class="track-result"><h3>${esc(d.statusLabel)}</h3><p><b>${esc(d.orderId)}</b></p><p>Hudud: ${esc(d.area)} • ${esc(d.deliverySlot)}</p><p>${d.items.map(x=>`${esc(x.name)} × ${x.qty}`).join('<br>')}</p><strong>${money(d.total)}</strong></div>`}catch(err){box.innerHTML=`<p class="error-text">${esc(err.message)}</p>`}}
function openCheckout(){if(!cart.length){alert('Savat bo‘sh.');return}closeCart();const areas=settings.delivery?.areas||[],slots=settings.delivery?.slots||[];$('#checkoutModal').innerHTML=`<div class="checkout-card"><button class="x" onclick="closeCheckout()">×</button><div class="checkout-head"><span class="eyebrow">BEPUL YETKAZIB BERISH</span><h2>Buyurtmani rasmiylashtirish</h2><p>Parkent tumani hududini tanlang. GPS lokatsiya ixtiyoriy, ammo tavsiya etiladi.</p></div><div class="checkout-grid"><form id="checkoutForm"><input name="name" placeholder="Ismingiz" required><input name="phone" type="tel" placeholder="+998 90 123 45 67" required><select name="area" required><option value="">Hududni tanlang *</option>${areas.map(a=>`<option>${esc(a)}</option>`).join('')}</select><textarea name="address" placeholder="Ko‘cha, uy va mo‘ljal *" required></textarea><select name="deliverySlot" required><option value="">Yetkazish vaqtini tanlang *</option>${slots.map(a=>`<option>${esc(a)}</option>`).join('')}</select><select name="payment" required><option value="">To‘lov turi *</option><option>Naqd</option><option>Karta / terminal</option><option>O‘tkazma</option></select><textarea name="comment" placeholder="Izoh (ixtiyoriy)"></textarea><input type="hidden" name="lat"><input type="hidden" name="lng"><button class="location-btn" type="button" onclick="getLocation()">Lokatsiyamni yuborish</button><div id="locationStatus" class="location-status">Lokatsiya hali olinmagan</div></form><aside><h3>Buyurtma</h3>${cart.map(x=>{const p=products.find(p=>Number(p.id)===Number(x.id));return `<div class="summary-line"><span>${esc(nameOf(p))} × ${x.qty}</span><b>${money(p.price*x.qty)}</b></div>`}).join('')}<div class="summary-line"><span>Chegirma</span><b>− ${money(promo.discount)}</b></div><div class="summary-line"><span>Yetkazish</span><b class="free">BEPUL</b></div><div class="summary-line grand"><span>Jami</span><b>${money(total())}</b></div><button class="btn primary" id="orderSubmit" onclick="submitOrder(event)">Buyurtmani tasdiqlash</button><div id="checkoutStatus"></div></aside></div></div>`;$('#checkoutModal').classList.add('show')}
function closeCheckout(){$('#checkoutModal').classList.remove('show')}
function getLocation(){const st=$('#locationStatus');if(!navigator.geolocation){st.textContent='Brauzer geolokatsiyani qo‘llamaydi.';return}st.textContent='Lokatsiya aniqlanmoqda...';navigator.geolocation.getCurrentPosition(pos=>{const f=$('#checkoutForm');f.elements.lat.value=pos.coords.latitude;f.elements.lng.value=pos.coords.longitude;st.innerHTML=`Lokatsiya olindi • <a target="_blank" href="https://maps.google.com/?q=${pos.coords.latitude},${pos.coords.longitude}">Xaritada ko‘rish</a>`},()=>{st.textContent='Lokatsiyaga ruxsat berilmadi. Manzilni qo‘lda kiriting.'},{enableHighAccuracy:true,timeout:10000})}
async function submitOrder(e){e.preventDefault();const f=$('#checkoutForm');if(!f.reportValidity())return;const btn=$('#orderSubmit'),status=$('#checkoutStatus'),fd=new FormData(f);btn.disabled=true;status.textContent='Buyurtma yuborilmoqda...';const order={customer:{name:fd.get('name'),phone:fd.get('phone'),area:fd.get('area'),address:fd.get('address'),deliverySlot:fd.get('deliverySlot'),payment:fd.get('payment'),comment:fd.get('comment'),lat:fd.get('lat'),lng:fd.get('lng')},items:cart.map(x=>({id:x.id,qty:x.qty})),promoCode:promo.code,language:lang};try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(order)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Xatolik');status.innerHTML=`<div class="success-box"><b>✅ Buyurtma qabul qilindi!</b><span>Raqam: ${esc(d.orderId)}</span><small>Bu raqamni saqlab qo‘ying — buyurtmani kuzatish uchun kerak.</small></div>`;cart=[];promo={code:'',discount:0};saveCart();renderCart();products.forEach(p=>{const ordered=order.items.find(x=>Number(x.id)===Number(p.id));if(ordered)p.stock=Math.max(0,Number(p.stock)-ordered.qty)});renderProducts();setTimeout(()=>closeCheckout(),3500)}catch(err){status.innerHTML=`<p class="error-text">${esc(err.message)}</p>`}finally{btn.disabled=false}}

$('#language').onchange=e=>{lang=e.target.value;localStorage.setItem('lang',lang);applySite();renderAll()};$('#searchInput').addEventListener('input',e=>{search=e.target.value;renderProducts()});$('#searchBtn').onclick=()=>{search=$('#searchInput').value;renderProducts();$('#products').scrollIntoView({behavior:'smooth'})};$$('.sort-pill').forEach(btn=>btn.onclick=()=>{sort=btn.dataset.sort;$$('.sort-pill').forEach(b=>b.classList.toggle('active',b===btn));renderProducts()});$('#cartBtn').onclick=openCart;$('#mobileStickyCart').onclick=openCart;$('#closeCart').onclick=closeCart;$('#overlay').onclick=closeCart;$('#checkout').onclick=openCheckout;$('#applyPromo').onclick=applyPromo;$('#favoritesBtn').onclick=showFavorites;$('#trackBtn').onclick=openTracking;$('#heroTrackBtn')&&($('#heroTrackBtn').onclick=openTracking);$('#footerTrack').onclick=e=>{e.preventDefault();openTracking()};$('#menuBtn').onclick=()=>$('#mobileNav').classList.toggle('open');$$('.mobile-nav a').forEach(a=>a.onclick=()=>$('#mobileNav').classList.remove('open'));
const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.08});$$('.reveal').forEach(x=>obs.observe(x));
loadCatalog();
