const defaultProducts=[
 {id:1,cat:"food",emoji:"🍚",name:{uz:"Premium guruch",ru:"Премиальный рис",en:"Premium rice"},price:45000,image:""},
 {id:2,cat:"food",emoji:"🍯",name:{uz:"Tabiiy asal",ru:"Натуральный мёд",en:"Natural honey"},price:78000,image:""},
 {id:3,cat:"food",emoji:"🫙",name:{uz:"Sof zaytun yog‘i",ru:"Оливковое масло",en:"Pure olive oil"},price:125000,image:""},
 {id:4,cat:"home",emoji:"🧺",name:{uz:"Uy uchun to‘plam",ru:"Набор для дома",en:"Home essentials set"},price:99000,image:""}
];
let products=JSON.parse(localStorage.getItem("iob_products")||"null")||defaultProducts;
const defaultCategories=[
 {id:"food",icon:"🍎",name:{uz:"Oziq-ovqat",ru:"Продукты",en:"Food"}},
 {id:"home",icon:"🏠",name:{uz:"Uy uchun",ru:"Для дома",en:"Home"}}
];
let categories=JSON.parse(localStorage.getItem("iob_categories")||"null")||defaultCategories;
function saveCategories(){localStorage.setItem("iob_categories",JSON.stringify(categories));}
function categoryById(id){return categories.find(c=>c.id===id)||categories[0]||{id:"other",icon:"🛍️",name:{uz:"Boshqa",ru:"Другое",en:"Other"}};}
function renderCategoryFilters(){
 const box=document.getElementById("categoryFilters"); if(!box)return;
 box.innerHTML=`<button class="filter ${currentFilter==="all"?"active":""}" data-filter="all">${tr[lang].all}</button>`+categories.map(c=>`<button class="filter ${currentFilter===c.id?"active":""}" data-filter="${c.id}">${c.iconImage?`<img src="${c.iconImage}" class="cat-icon-img">`:c.icon} ${c.name[lang]}</button>`).join("");
 box.querySelectorAll(".filter").forEach(b=>b.onclick=()=>renderProducts(b.dataset.filter));
}

const defaultSettings={
  hero:{uz:{title:"Baraka bilan tanlang.",text:"Siz uchun saralangan sifatli mahsulotlar. Zamonaviy xarid tajribasi, ishonchli xizmat va tez yetkazib berish."},ru:{title:"Выбирайте с баракатом.",text:"Качественные товары, отобранные для вас. Современный шопинг, надёжный сервис и быстрая доставка."},en:{title:"Choose with baraka.",text:"Quality products selected for you. A modern shopping experience, reliable service and fast delivery."}},
  catalog:{uz:"Mashhur mahsulotlar",ru:"Популярные товары",en:"Popular products"},
  about:{uz:{title:"Baraka — sifat va ishonchdan boshlanadi.",text:"Imom Ota Baraka brendi mijozga sifatli mahsulot, shaffof xizmat va yoqimli xarid tajribasini taqdim etishga intiladi."},ru:{title:"Баракат начинается с качества и доверия.",text:"Imom Ota Baraka стремится дать клиентам качественные товары, прозрачный сервис и приятный опыт покупок."},en:{title:"Baraka starts with quality and trust.",text:"Imom Ota Baraka aims to provide quality products, transparent service and a pleasant shopping experience."}},
  contact:{uz:{title:"Yangiliklardan xabardor bo‘ling.",text:"Aksiyalar va yangi mahsulotlar haqida birinchi bo‘lib bilib oling."},ru:{title:"Будьте в курсе новостей.",text:"Узнавайте первыми об акциях и новых товарах."},en:{title:"Stay in the loop.",text:"Be the first to hear about offers and new products."}},
  phone:"+998901361211",telegram:"https://t.me/imomotabaraka",email:"info@imomotamarket.uz"
};
let settings=JSON.parse(localStorage.getItem("iob_settings")||"null")||defaultSettings;
function getText(path, fallback){const parts=path.split('.');let o=settings;for(const p of parts)o=o?.[p];return o ?? fallback;}
function refreshSettings(){
  const heroTitle=document.querySelector('[data-i18n="heroTitle"]'); if(heroTitle) heroTitle.textContent=getText('hero.'+lang+'.title',defaultSettings.hero[lang].title);
  const heroText=document.querySelector('[data-i18n="heroText"]'); if(heroText) heroText.textContent=getText('hero.'+lang+'.text',defaultSettings.hero[lang].text);
  const catalogTitle=document.querySelector('[data-i18n="catalogTitle"]'); if(catalogTitle) catalogTitle.textContent=getText('catalog.'+lang,defaultSettings.catalog[lang]);
  const aboutTitle=document.querySelector('[data-i18n="aboutTitle"]'); if(aboutTitle) aboutTitle.textContent=getText('about.'+lang+'.title',defaultSettings.about[lang].title);
  const aboutText=document.querySelector('[data-i18n="aboutText"]'); if(aboutText) aboutText.textContent=getText('about.'+lang+'.text',defaultSettings.about[lang].text);
  const contactTitle=document.querySelector('[data-i18n="contactTitle"]'); if(contactTitle) contactTitle.textContent=getText('contact.'+lang+'.title',defaultSettings.contact[lang].title);
  const contactText=document.querySelector('[data-i18n="contactText"]'); if(contactText) contactText.textContent=getText('contact.'+lang+'.text',defaultSettings.contact[lang].text);
  const phone=document.getElementById('contactPhone'); if(phone){phone.textContent=formatPhone(settings.phone);phone.href='tel:'+settings.phone.replace(/\D/g,'');}
  const tg=document.getElementById('contactTelegram'); if(tg){tg.textContent=settings.telegram.replace(/^https?:\/\//,'');tg.href=settings.telegram;}
  const em=document.getElementById('contactEmail'); if(em){em.textContent=settings.email;em.href='mailto:'+settings.email;}
}
function formatPhone(p){const d=(p||'').replace(/\D/g,''); if(d.length===12&&d.startsWith('998')) return '+998 '+d.slice(3,5)+' '+d.slice(5,8)+' '+d.slice(8,10)+' '+d.slice(10); return p||'';}

const tr={
uz:{home:"Bosh sahifa",products:"Mahsulotlar",about:"Biz haqimizda",contact:"Aloqa",eyebrow:"HALOL • SIFATLI • ISHONCHLI",heroTitle:"Baraka bilan tanlang.",heroText:"Siz uchun saralangan sifatli mahsulotlar. Zamonaviy xarid tajribasi, ishonchli xizmat va tez yetkazib berish.",shopNow:"Xarid qilish",learnMore:"Batafsil",quality:"Sifat nazorati",delivery:"Tez yetkazish",support:"24/7 aloqa",welcome:"Xush kelibsiz",catalogEyebrow:"SARALANGAN KATALOG",catalogTitle:"Mashhur mahsulotlar",all:"Barchasi",food:"Oziq-ovqat",homeCat:"Uy uchun",aboutEyebrow:"BIZNING QADRIYATLAR",aboutTitle:"Baraka — sifat va ishonchdan boshlanadi.",aboutText:"Imom Ota Baraka brendi mijozga sifatli mahsulot, shaffof xizmat va yoqimli xarid tajribasini taqdim etishga intiladi.",stat1:"Sifatga e’tibor",stat2:"Mijozlar yordami",stat3:"Til",contactTitle:"Yangiliklardan xabardor bo‘ling.",contactText:"Aksiyalar va yangi mahsulotlar haqida birinchi bo‘lib bilib oling.",subscribe:"Obuna bo‘lish",links:"Havolalar",rights:"Barcha huquqlar himoyalangan.",cart:"Savat",total:"Jami",checkout:"Buyurtma berish",add:"Savatga qo‘shish"},
ru:{home:"Главная",products:"Товары",about:"О нас",contact:"Контакты",eyebrow:"ЧЕСТНО • КАЧЕСТВЕННО • НАДЁЖНО",heroTitle:"Выбирайте с баракатом.",heroText:"Качественные товары, отобранные для вас. Современный шопинг, надёжный сервис и быстрая доставка.",shopNow:"Покупать",learnMore:"Подробнее",quality:"Контроль качества",delivery:"Быстрая доставка",support:"Поддержка 24/7",welcome:"Добро пожаловать",catalogEyebrow:"ОТОБРАННЫЙ КАТАЛОГ",catalogTitle:"Популярные товары",all:"Все",food:"Продукты",homeCat:"Для дома",aboutEyebrow:"НАШИ ЦЕННОСТИ",aboutTitle:"Баракат начинается с качества и доверия.",aboutText:"Imom Ota Baraka стремится дать клиентам качественные товары, прозрачный сервис и приятный опыт покупок.",stat1:"Внимание к качеству",stat2:"Поддержка клиентов",stat3:"Языка",contactTitle:"Будьте в курсе новостей.",contactText:"Узнавайте первыми об акциях и новых товарах.",subscribe:"Подписаться",links:"Ссылки",rights:"Все права защищены.",cart:"Корзина",total:"Итого",checkout:"Оформить заказ",add:"В корзину"},
en:{home:"Home",products:"Products",about:"About us",contact:"Contact",eyebrow:"HONEST • QUALITY • TRUST",heroTitle:"Choose with baraka.",heroText:"Quality products selected for you. A modern shopping experience, reliable service and fast delivery.",shopNow:"Shop now",learnMore:"Learn more",quality:"Quality control",delivery:"Fast delivery",support:"24/7 support",welcome:"Welcome",catalogEyebrow:"CURATED CATALOG",catalogTitle:"Popular products",all:"All",food:"Food",homeCat:"For home",aboutEyebrow:"OUR VALUES",aboutTitle:"Baraka starts with quality and trust.",aboutText:"Imom Ota Baraka aims to provide quality products, transparent service and a pleasant shopping experience.",stat1:"Quality first",stat2:"Customer support",stat3:"Languages",contactTitle:"Stay in the loop.",contactText:"Be the first to hear about offers and new products.",subscribe:"Subscribe",links:"Links",rights:"All rights reserved.",cart:"Cart",total:"Total",checkout:"Checkout",add:"Add to cart"}
};
let lang=localStorage.getItem("lang")||"uz", cart=[], currentFilter="all";
function getLogo(){return localStorage.getItem("iob_logo")||"logo.png";}
function saveProducts(){localStorage.setItem("iob_products",JSON.stringify(products));}
function refreshLogo(){document.querySelectorAll("img[alt*='logo' i], .brand img, .hero-card img, .story-image img, .footer-brand img").forEach(i=>i.src=getLogo());}
const money=n=>new Intl.NumberFormat(lang==="en"?"en-US":"ru-RU").format(n)+" "+(lang==="en"?"UZS":"so‘m");
function applyLang(){document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=tr[lang][e.dataset.i18n]);refreshSettings();renderCategoryFilters();renderProducts(currentFilter);renderCart();}
let reviews=JSON.parse(localStorage.getItem("iob_reviews")||"{}")||{};
function saveReviews(){localStorage.setItem("iob_reviews",JSON.stringify(reviews));}
function reviewStats(id){const a=reviews[id]||[];return {count:a.length,avg:a.length?a.reduce((s,r)=>s+Number(r.rating||0),0)/a.length:0};}
function starsHtml(rating, interactive=false, id=""){let out="";for(let i=1;i<=5;i++)out+=interactive?`<button type="button" class="star-btn ${i<=rating?"on":""}" onclick="setRating(${id},${i})">★</button>`:`<span class="star ${i<=Math.round(rating)?"on":""}">★</span>`;return out;}
let selectedRating={};
function setRating(id,n){selectedRating[id]=n;const box=document.getElementById(`reviewStars-${id}`);if(box)box.innerHTML=starsHtml(n,true,id);}
function openReview(id){const p=products.find(x=>x.id===id);if(!p)return;selectedRating[id]=0;const st=reviewStats(id);const old=(reviews[id]||[]).map(r=>`<div class="review"><div class="review-top"><b>${r.name||"Mijoz"}</b><span>${starsHtml(Number(r.rating||0))}</span></div><p>${escapeHtml(r.comment||"")}</p><small>${r.date||""}</small></div>`).join("");const modal=document.getElementById("reviewModal");modal.innerHTML=`<div class="review-dialog"><button class="review-close" onclick="closeReview()">×</button><div class="product-cat">${categoryById(p.cat).name[lang]}</div><h2>${p.name[lang]}</h2><div class="review-summary"><strong>${st.avg?st.avg.toFixed(1):"0.0"}</strong><span>${starsHtml(st.avg)}</span><small>${st.count} ${lang==="uz"?"ta baho":lang==="ru"?"отзывов":"reviews"}</small></div><div class="review-form"><input id="reviewName" placeholder="${lang==="uz"?"Ismingiz":lang==="ru"?"Ваше имя":"Your name"}"><div id="reviewStars-${id}" class="review-stars-input">${starsHtml(0,true,id)}</div><textarea id="reviewComment" placeholder="${lang==="uz"?"Fikringizni yozing...":lang==="ru"?"Напишите ваш отзыв...":"Write your review..."}"></textarea><button class="btn primary" onclick="submitReview(${id})">${lang==="uz"?"Bahoni yuborish":lang==="ru"?"Оставить отзыв":"Submit review"}</button></div><div class="reviews-list">${old||`<p class="muted">${lang==="uz"?"Hali sharhlar yo‘q.":lang==="ru"?"Отзывов пока нет.":"No reviews yet."}</p>`}</div></div>`;modal.classList.add("show");}
function closeReview(){const m=document.getElementById("reviewModal");if(m)m.classList.remove("show");}
function submitReview(id){const rating=selectedRating[id]||0,comment=document.getElementById("reviewComment").value.trim(),name=document.getElementById("reviewName").value.trim()||"Mijoz";if(!rating){alert(lang==="uz"?"Yulduzcha bahosini tanlang.":lang==="ru"?"Выберите оценку звёздами.":"Please choose a star rating.");return}if(!comment){alert(lang==="uz"?"Kamentariya yozing.":lang==="ru"?"Напишите комментарий.":"Please write a comment.");return}if(!reviews[id])reviews[id]=[];reviews[id].unshift({name,rating,comment,date:new Date().toLocaleDateString()});saveReviews();closeReview();renderProducts(currentFilter);}
function escapeHtml(x){return String(x).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));}
function renderProducts(filter="all"){currentFilter=filter;renderCategoryFilters();const grid=document.getElementById("productGrid");grid.innerHTML=products.filter(p=>filter==="all"||p.cat===filter).map(p=>{const c=categoryById(p.cat);const st=reviewStats(p.id),stock=Number(p.stock??9999); return `<article class="product reveal visible"><div class="product-img">${p.image?`<img src="${p.image}" alt="${p.name[lang]}">`:p.emoji}</div><div class="product-info"><div class="product-cat">${c.iconImage?`<img src="${c.iconImage}" class="cat-icon-img">`:c.icon} ${c.name[lang]}</div><h3>${p.name[lang]}</h3><div class="rating-line"><span>${starsHtml(st.avg)}</span><small>${st.count}</small></div><div class="price">${money(p.price)}</div><div class="muted" style="font-size:12px;margin-bottom:8px">${lang==="uz"?"Omborda":lang==="ru"?"В наличии":"In stock"}: ${stock}</div><button class="add" ${stock<=0?'disabled':''} onclick="addToCart(${p.id})">${stock<=0?(lang==="uz"?"Tugagan":lang==="ru"?"Нет в наличии":"Out of stock"):tr[lang].add}</button><button class="review-open" onclick="openReview(${p.id})">★ ${lang==="uz"?"Baho va kamentariya":lang==="ru"?"Оценить и оставить отзыв":"Rate & review"}</button></div></article>`}).join("");}
function addToCart(id){const p=products.find(p=>p.id===id);if(!p)return;const inCart=cart.filter(x=>x.id===id).length;if(Number(p.stock??9999)<=inCart){alert(lang==="uz"?"Omborda yetarli mahsulot yo‘q.":lang==="ru"?"Недостаточно товара на складе.":"Not enough stock.");return;}cart.push(p);renderCart();openCart();}
function renderCart(){document.getElementById("cartCount").textContent=cart.length;const box=document.getElementById("cartItems");box.innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-item"><span>${p.emoji} ${p.name[lang]}</span><b>${money(p.price)}</b><button onclick="removeCart(${i})">×</button></div>`).join(""):`<p style="color:#7a857e">${lang==="uz"?"Savat hozircha bo‘sh.":lang==="ru"?"Корзина пока пуста.":"Your cart is empty."}</p>`;document.getElementById("cartTotal").textContent=money(cart.reduce((s,p)=>s+p.price,0));}
function removeCart(i){cart.splice(i,1);renderCart();}
function openCart(){document.getElementById("cartPanel").classList.add("open");document.getElementById("overlay").classList.add("show")}
function closeCart(){document.getElementById("cartPanel").classList.remove("open");document.getElementById("overlay").classList.remove("show")}
document.getElementById("language").value=lang;document.getElementById("language").onchange=e=>{lang=e.target.value;localStorage.setItem("lang",lang);applyLang()};

document.getElementById("cartBtn").onclick=openCart;document.getElementById("closeCart").onclick=closeCart;document.getElementById("overlay").onclick=closeCart;
document.getElementById("menuBtn").onclick=()=>document.getElementById("mobileNav").classList.toggle("open");
document.querySelectorAll(".mobile-nav a").forEach(a=>a.onclick=()=>document.getElementById("mobileNav").classList.remove("open"));
document.getElementById("subscribe").onsubmit=e=>{e.preventDefault();alert(lang==="uz"?"Rahmat! Siz obuna bo‘ldingiz.":lang==="ru"?"Спасибо! Вы подписались.":"Thank you! You are subscribed.")};
function openCheckout(){
 if(!cart.length){alert(lang==="uz"?"Savat bo‘sh.":lang==="ru"?"Корзина пуста.":"Cart is empty.");return;}
 closeCart();
 const total=cart.reduce((s,p)=>s+p.price,0), modal=document.getElementById("checkoutModal");
 const labels=lang==="uz"?{title:"Buyurtmani rasmiylashtirish",sub:"Ma’lumotlaringizni kiriting. Buyurtma Telegram bot orqali menejerga yuboriladi.",name:"Ismingiz",phone:"Telefon raqamingiz",address:"Yetkazib berish manzili",payment:"To‘lov turi",cash:"Naqd",card:"Karta / terminal",transfer:"O‘tkazma",comment:"Izoh (ixtiyoriy)",send:"Buyurtmani yuborish",total:"Jami"}:lang==="ru"?{title:"Оформление заказа",sub:"Введите данные. Заказ будет отправлен менеджеру через Telegram-бот.",name:"Ваше имя",phone:"Номер телефона",address:"Адрес доставки",payment:"Способ оплаты",cash:"Наличные",card:"Карта / терминал",transfer:"Перевод",comment:"Комментарий (необязательно)",send:"Отправить заказ",total:"Итого"}:{title:"Checkout",sub:"Enter your details. The order will be sent to the manager via Telegram bot.",name:"Your name",phone:"Phone number",address:"Delivery address",payment:"Payment method",cash:"Cash",card:"Card / terminal",transfer:"Transfer",comment:"Comment (optional)",send:"Send order",total:"Total"};
 modal.innerHTML=`<div class="checkout-dialog"><button class="checkout-close" type="button" onclick="closeCheckout()">×</button><h2>${labels.title}</h2><p class="muted">${labels.sub}</p><div class="checkout-summary">${cart.map(p=>`<div class="checkout-summary-row"><span>${escapeHtml(p.name[lang])}</span><b>${money(p.price)}</b></div>`).join("")}<div class="checkout-summary-row"><strong>${labels.total}</strong><strong>${money(total)}</strong></div></div><form id="checkoutForm" class="checkout-form"><input name="name" placeholder="${labels.name}" required maxlength="80"><input name="phone" type="tel" placeholder="${labels.phone}" required maxlength="30"><textarea name="address" placeholder="${labels.address}" required maxlength="300"></textarea><select name="payment" required><option value="">${labels.payment}</option><option>${labels.cash}</option><option>${labels.card}</option><option>${labels.transfer}</option></select><textarea name="comment" placeholder="${labels.comment}" maxlength="500"></textarea><button class="btn primary" id="orderSubmit" type="submit">${labels.send}</button><div id="checkoutStatus" class="checkout-status"></div></form></div>`;
 modal.classList.add("show"); document.getElementById("checkoutForm").onsubmit=submitOrder;
}
function closeCheckout(){document.getElementById("checkoutModal").classList.remove("show");}
async function submitOrder(e){
 e.preventDefault(); const f=e.currentTarget, btn=document.getElementById("orderSubmit"), status=document.getElementById("checkoutStatus"), fd=new FormData(f);
 const order={customer:{name:fd.get("name"),phone:fd.get("phone"),address:fd.get("address"),payment:fd.get("payment"),comment:fd.get("comment")},items:cart.map(p=>({id:p.id,name:p.name[lang],price:p.price})),total:cart.reduce((s,p)=>s+p.price,0),language:lang};
 btn.disabled=true; status.className="checkout-status"; status.textContent=lang==="uz"?"Yuborilmoqda...":lang==="ru"?"Отправляется...":"Sending...";
 try{const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(order)}); const data=await r.json().catch(()=>({})); if(!r.ok)throw new Error(data.error||"Send failed"); status.className="checkout-status ok";status.textContent=(lang==="uz"?"Buyurtma qabul qilindi. Raqam: ":lang==="ru"?"Заказ принят. Номер: ":"Order received. Number: ")+(data.orderId||"");cart=[];renderCart();setTimeout(closeCheckout,1800)}catch(err){status.className="checkout-status error";status.textContent=lang==="uz"?"Buyurtma yuborilmadi. Server/Bot sozlamalarini tekshiring.":lang==="ru"?"Заказ не отправлен. Проверьте настройки сервера/бота.":"Order was not sent. Check server/bot settings."}finally{btn.disabled=false}
}
document.getElementById("checkout").onclick=openCheckout;
const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>obs.observe(x));
async function syncOnlineCatalog(){try{const r=await fetch("/api/catalog",{cache:"no-store"});if(!r.ok)return;const d=await r.json();if(Array.isArray(d.products)&&d.products.length)products=d.products;if(Array.isArray(d.categories)&&d.categories.length)categories=d.categories;if(d.settings)settings=d.settings;if(d.logo)localStorage.setItem("iob_logo",d.logo);localStorage.setItem("iob_products",JSON.stringify(products));localStorage.setItem("iob_categories",JSON.stringify(categories));localStorage.setItem("iob_settings",JSON.stringify(settings));applyLang();refreshLogo();}catch(e){console.warn("Online catalog unavailable",e)}}
applyLang(); refreshLogo(); syncOnlineCatalog();