'use strict';
const crypto=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
const ipaddr=require('ipaddr.js');
const sha=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
const equal=(a,b)=>{const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&x.length>0&&crypto.timingSafeEqual(x,y)};
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
function cookies(req){const out={};for(const item of String(req.headers.cookie||'').split(';')){const i=item.indexOf('=');if(i>0){try{out[item.slice(0,i).trim()]=decodeURIComponent(item.slice(i+1))}catch{}}}return out;}
function publicIp(raw){try{let a=ipaddr.parse(String(raw).replace(/^\[|\]$/g,''));if(a.kind()==='ipv6'&&a.isIPv4MappedAddress())a=a.toIPv4Address();return a.range()==='unicast';}catch{return false}}
function base32(buf){const abc='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,v=0,out='';for(const b of buf){v=(v<<8)|b;bits+=8;while(bits>=5){out+=abc[(v>>>(bits-5))&31];bits-=5}}if(bits)out+=abc[(v<<(5-bits))&31];return out}
function unbase32(s){let bits=0,v=0,out=[];for(const ch of String(s).toUpperCase()){const n='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(ch);if(n<0)throw new Error('Invalid base32');v=(v<<5)|n;bits+=5;if(bits>=8){out.push((v>>>(bits-8))&255);bits-=8}}return Buffer.from(out)}
function totp(secret,step=Math.floor(Date.now()/30000)){const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(step));const h=crypto.createHmac('sha1',unbase32(secret)).update(b).digest(),i=h[19]&15;return String((h.readUInt32BE(i)&0x7fffffff)%1000000).padStart(6,'0')}

function createSecurity({pool,dataDir,secret,users}){
 const file=path.join(dataDir,'security-state.json'),memory=new Map(),key=crypto.createHash('sha256').update(secret).digest();
 function save(){if(pool)return;fs.mkdirSync(dataDir,{recursive:true});const tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify([...memory]),{mode:0o600});fs.renameSync(tmp,file)}
 async function init(){if(pool){await pool.query('CREATE TABLE IF NOT EXISTS zarbuloq_security (k TEXT PRIMARY KEY,v JSONB NOT NULL,expires BIGINT NOT NULL)');}else{try{for(const [k,v] of JSON.parse(fs.readFileSync(file,'utf8')))memory.set(k,v)}catch(e){if(e.code!=='ENOENT')throw e}}}
 async function get(k){if(pool){const r=await pool.query('SELECT v FROM zarbuloq_security WHERE k=$1 AND expires>$2',[k,Date.now()]);return r.rows[0]?.v||null}const row=memory.get(k);return row&&row.expires>Date.now()?row.v:null}
 async function set(k,v,ttl){const expires=Date.now()+ttl;if(pool)await pool.query('INSERT INTO zarbuloq_security(k,v,expires) VALUES($1,$2,$3) ON CONFLICT(k) DO UPDATE SET v=$2,expires=$3',[k,JSON.stringify(v),expires]);else{memory.set(k,{v,expires});save()}}
 async function del(k){if(pool)await pool.query('DELETE FROM zarbuloq_security WHERE k=$1',[k]);else{memory.delete(k);save()}}
 async function once(k,ttl){if(pool){const r=await pool.query('INSERT INTO zarbuloq_security(k,v,expires) VALUES($1,\'{}\',$2) ON CONFLICT DO NOTHING RETURNING k',[k,Date.now()+ttl]);return r.rowCount===1}if(memory.has(k))return false;await set(k,{},ttl);return true}
 async function hit(name,id,windowMs,max){const now=Date.now(),bucket=Math.floor(now/windowMs),k='rate:'+name+':'+sha(id)+':'+bucket;let count;
  if(pool){const r=await pool.query("INSERT INTO zarbuloq_security(k,v,expires) VALUES($1,'{\"n\":1}',$2) ON CONFLICT(k) DO UPDATE SET v=jsonb_build_object('n',(zarbuloq_security.v->>'n')::int+1) RETURNING v",[k,(bucket+2)*windowMs]);count=r.rows[0].v.n}
  else{const row=memory.get(k);count=Number(row?.v?.n||0)+1;memory.set(k,{v:{n:count},expires:Date.now()+windowMs*2});save()}
  return count<=max;
 }
 const timer=setInterval(()=>{if(pool)pool.query('DELETE FROM zarbuloq_security WHERE expires<$1',[Date.now()]).catch(()=>{});else{for(const [k,r] of memory)if(r.expires<Date.now())memory.delete(k);save()}},60000);timer.unref();
 const limiter=(name,max,ms=60000)=>asyncRoute(async(req,res,next)=>{if(!await hit(name,req.ip||req.socket.remoteAddress,ms,max)){res.set('Retry-After',String(Math.ceil(ms/1000)));return res.status(429).json({error:'Juda ko‘p urinish. Birozdan keyin qayta urinib ko‘ring.'})}next()});
 function encrypted(s){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key,iv),b=Buffer.concat([c.update(s,'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),b]).toString('base64')}
 function decrypted(s){const b=Buffer.from(s,'base64'),c=crypto.createDecipheriv('aes-256-gcm',key,b.subarray(0,12));c.setAuthTag(b.subarray(12,28));return Buffer.concat([c.update(b.subarray(28)),c.final()]).toString()}
 function cookie(req,name,value,age){return `${name}=${value}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${age}${req.secure||process.env.NODE_ENV==='production'?'; Secure':''}`}
 function signature(s){return crypto.createHmac('sha256',secret).update(s).digest('hex')}
 function client(req,res,create=false){let t=String(req.get('X-Client-Token')||cookies(req).z_client||'');let [id,exp,sig]=t.split('.');if(!/^[a-f0-9]{48}$/.test(id||'')||!Number.isSafeInteger(Number(exp))||Number(exp)<Date.now()||!equal(sig,signature(`client:${id}.${exp}`))){if(!create)return '';id=crypto.randomBytes(24).toString('hex');exp=String(Date.now()+180*86400000);t=id+'.'+exp+'.'+signature(`client:${id}.${exp}`);res.append('Set-Cookie',cookie(req,'z_client',t,180*86400))}req.clientToken=t;return sha(id)}
 function allowedOrigin(req){const source=req.get('origin')||req.get('referer');if(!source)return false;try{const origin=new URL(source).origin;const allowed=['https://zarbuloq.uz','https://www.zarbuloq.uz'];if(process.env.NODE_ENV!=='production')allowed.push('http://'+req.get('host'));return allowed.includes(origin)}catch{return false}}
 const originGuard=(req,res,next)=>{if(['GET','HEAD','OPTIONS'].includes(req.method))return next();if(req.path==='/api/telegram/webhook')return next();if(req.path.startsWith('/api/admin/')){if(/^Bearer\s+\S+$/i.test(req.get('authorization')||''))return next();if(!allowedOrigin(req))return res.status(403).json({error:'So‘rov manbasi tasdiqlanmadi'})}else if(req.get('origin')&&!allowedOrigin(req))return res.status(403).json({error:'So‘rov manbasi tasdiqlanmadi'});next()};
 function fingerprint(u){return sha(u.username+'|'+u.role+'|'+u.password)}
 function token(req){return cookies(req).iob_admin||String(req.get('authorization')||'').replace(/^Bearer\s+/i,'')||''}
 const requireAdmin=asyncRoute(async(req,res,next)=>{if(req.adminUser)return next();const t=token(req);if(!/^[a-f0-9]{64}$/.test(t))return res.status(401).json({error:'Qayta kiring'});const s=await get('session:'+sha(t)),u=users.find(x=>x.username===s?.user);if(!s||!u||s.fp!==fingerprint(u)||Date.now()-s.last>30*60000)return res.status(401).json({error:'Sessiya tugagan. Qayta kiring'});if(Date.now()-s.last>60000){s.last=Date.now();await set('session:'+sha(t),s,Math.max(1,s.exp-Date.now()))}req.adminUser=u.username;req.adminRole=u.role;req.adminSession=s;req.adminToken=t;next()});
 function roleGuard(req,res,next){if(!req.path.startsWith('/api/admin/')||['/api/admin/login','/api/admin/logout'].includes(req.path))return next();if(req.adminRole==='admin')return next();const p=req.path;const read=['GET','HEAD'].includes(req.method);let ok=['/api/admin/me','/api/admin/logout','/api/admin/dashboard'].includes(p);if(req.adminRole==='stock')ok=ok||(read&&/^\/api\/admin\/(products(?:\/|$)|inventory-report\.xls$|products-import-template$)/.test(p))||/^\/api\/admin\/(catalog$|products\/\d+$|inventory-receive$|products-import-(preview|excel)$)/.test(p);if(req.adminRole==='operator')ok=ok||/^\/api\/admin\/(orders\/|order-complaints(?:\/|$)|chats(?:\/|$))/.test(p);if(!ok)return res.status(403).json({error:'Bu amal faqat administrator uchun'});next()}
 async function mfaCheck(user,code){const row=await get('mfa:'+user);if(!row)return true;const secret=decrypted(row.secret);const now=Math.floor(Date.now()/30000);for(let t=now-1;t<=now+1;t++)if(equal(code,totp(secret,t)))return once('otp:'+sha(user)+':'+t,120000);const h=sha(String(code).replace(/\s/g,''));if(row.recovery.includes(h)){if(!await once('recovery:'+sha(user)+':'+h,3650*86400000))return false;row.recovery=row.recovery.filter(x=>x!==h);await set('mfa:'+user,row,3650*86400000);return true}return false}
 function passwordOK(u,p){return u&&u.password&&u.password!=='change-me'&&u.password.length>=8&&equal(u.password,p)}
 const login=asyncRoute(async(req,res)=>{const name=String(req.body?.username||'').trim().slice(0,80),u=users.find(x=>x.username===name);if(!await hit('login-user',name,15*60000,12))return res.status(429).json({error:'Kirish vaqtincha cheklangan'});if(!passwordOK(u,req.body?.password))return res.status(401).json({error:'Login yoki parol noto‘g‘ri'});if(!await mfaCheck(name,String(req.body?.otp||'')))return res.status(401).json({error:'Authenticator kodi yoki tiklash kodi kerak',mfaRequired:true});const t=crypto.randomBytes(32).toString('hex'),exp=Date.now()+8*3600000;await set('session:'+sha(t),{user:name,fp:fingerprint(u),last:Date.now(),exp},8*3600000);res.append('Set-Cookie',cookie(req,'iob_admin',t,8*3600));res.set('Cache-Control','no-store');res.json({ok:true,user:name,role:u.role,expiresAt:exp})});
 const logout=asyncRoute(async(req,res)=>{await del('session:'+sha(token(req)));res.append('Set-Cookie',cookie(req,'iob_admin','',0));res.json({ok:true})});
 function routes(app){
  app.post('/api/client-session',limiter('client-session',20),asyncRoute(async(req,res)=>{client(req,res,true);res.set('Cache-Control','no-store');res.json({ok:true,clientToken:req.clientToken})}));
  app.get('/api/admin/security',requireAdmin,asyncRoute(async(req,res)=>res.json({ok:true,mfaEnabled:!!await get('mfa:'+req.adminUser),sessionHours:8,idleMinutes:30,durableStore:!!pool})));
  app.post('/api/admin/security/mfa/setup',requireAdmin,limiter('mfa-setup',5,600000),asyncRoute(async(req,res)=>{if(await get('mfa:'+req.adminUser))return res.status(409).json({error:'2FA allaqachon yoqilgan'});const u=users.find(x=>x.username===req.adminUser);if(!passwordOK(u,req.body?.password))return res.status(401).json({error:'Parol noto‘g‘ri'});const s=base32(crypto.randomBytes(20));await set('pending-mfa:'+sha(req.adminToken),{secret:encrypted(s)},10*60000);res.json({ok:true,secret:s,uri:'otpauth://totp/Zarbuloq:'+encodeURIComponent(req.adminUser)+'?secret='+s+'&issuer=Zarbuloq'})}));
  app.post('/api/admin/security/mfa/confirm',requireAdmin,limiter('mfa-confirm',8,600000),asyncRoute(async(req,res)=>{if(await get('mfa:'+req.adminUser))return res.status(409).json({error:'2FA yoqilgan'});const row=await get('pending-mfa:'+sha(req.adminToken));if(!row)return res.status(400).json({error:'Avval sozlashni boshlang'});const s=decrypted(row.secret),code=String(req.body?.otp||''),t=Math.floor(Date.now()/30000);if(![-1,0,1].some(d=>equal(totp(s,t+d),code)))return res.status(400).json({error:'Kod noto‘g‘ri'});const codes=Array.from({length:8},()=>crypto.randomBytes(10).toString('hex'));await set('mfa:'+req.adminUser,{secret:row.secret,recovery:codes.map(sha)},3650*86400000);await del('pending-mfa:'+sha(req.adminToken));await revokeAll(req.adminUser,req.adminToken);res.json({ok:true,recoveryCodes:codes})}));
  app.post('/api/admin/security/logout-all',requireAdmin,asyncRoute(async(req,res)=>{await revokeAll(req.adminUser);res.append('Set-Cookie',cookie(req,'iob_admin','',0));res.json({ok:true})}));
 }
 async function revokeAll(user,except=''){if(pool)await pool.query("DELETE FROM zarbuloq_security WHERE k LIKE 'session:%' AND v->>'user'=$1 AND k<>$2",[user,'session:'+sha(except)]);else{for(const [k,r]of memory)if(k.startsWith('session:')&&r.v.user===user&&k!=='session:'+sha(except))memory.delete(k);save()}}
 return {init,limiter,hit,client,originGuard,requireAdmin,roleGuard,login,logout,routes,cookies,publicIp,asyncRoute};
}
module.exports={createSecurity,publicIp,totp,equal};
