const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const source=fs.readFileSync(require('node:path').join(__dirname,'../server.js'),'utf8');
function fixture(){
 const db={settings:{delivery:{areas:['Parkent']}},products:[{id:1,name:{uz:'A'},stock:5,price:100000},{id:2,name:{uz:'B'},stock:1,price:100000}],orders:[]};
 let route,writes=0;const ctx={console,crypto,app:{post:(p,l,h)=>route=h},publicWriteLimiter(){},readDb:()=>db,clean:(s,n)=>String(s??'').trim().slice(0,n),checkParkentLocation:async()=>{await new Promise(r=>setTimeout(r,5));return true},orderPermission:()=>true,publicOrderView:o=>o,productSaleInfo:(d,p)=>({price:p.price,basePrice:p.price,discount:0}),validatePromo:()=>({ok:true,discount:0}),security:{client:()=>({id:'owner'})},audit(){},writeDb:async()=>{writes++;await new Promise(r=>setTimeout(r,5))},BOT_TOKEN:'',CHAT_ID:'',money:String,normalizeOrderStatus:s=>s,pushOrderHistory(){},broadcastAppRealtime(){}};
 vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('const orderRequestLocks='),source.indexOf("app.patch('/api/admin/orders/:id/status'")),ctx);
 const good={deviceId:'device',clientRequestId:'request',source:'web',customer:{name:'Akbarshoh Akramov',phone:'901234567',address:'Bog 10',area:'Parkent',payment:'Naqd',lat:41.294,lng:69.676,locationMethod:'map',locationConfirmed:true},items:[{id:1,qty:1}]};
 return {db,ctx,writes:()=>writes,submit:async(change={})=>{let status=200,result;await route({body:{...structuredClone(good),...change}},{status(n){status=n;return this},json(d){result=d;return this}});return {status,result}}};
}
test('same request concurrently creates exactly one order',async()=>{const f=fixture();const r=await Promise.all(Array.from({length:5},()=>f.submit()));assert(r.every(x=>x.status===200));assert.equal(new Set(r.map(x=>x.result.orderId)).size,1);assert.equal(f.db.orders.length,1);assert.equal(f.writes(),1)});
test('duplicate product rows use combined quantity and reject overselling',async()=>{const f=fixture();const r=await f.submit({items:[{id:1,qty:3},{id:1,qty:3}]});assert.equal(r.status,400);assert.equal(f.db.orders.length,0);const ok=await f.submit({items:[{id:1,qty:2},{id:1,qty:2}]});assert.equal(ok.status,200);assert.equal(ok.result.order.items.length,1);assert.equal(ok.result.order.items[0].qty,4)});
test('unknown product and invalid quantities do not silently become orders',async()=>{for(const items of [[{id:999,qty:1}],[{id:1,qty:0}],[{id:1,qty:-1}],[{id:1,qty:1.5}],[null]]){const f=fixture();assert.equal((await f.submit({items})).status,400);assert.equal(f.db.orders.length,0)}});
test('failed later stock line leaves all earlier stock and status unchanged',async()=>{const f=fixture();f.db.orders.push({orderId:'x',status:'new',items:[{id:1,qty:2},{id:2,qty:2}]});await assert.rejects(f.ctx.updateOrderStatus('x','delivery'),/omborda/);assert.equal(f.db.products[0].stock,5);assert.equal(f.db.products[1].stock,1);assert.equal(f.db.orders[0].status,'new');assert.equal(f.writes(),0)});
test('successful status deducts once and cancellation restores stock',async()=>{const f=fixture();f.db.orders.push({orderId:'x',status:'new',items:[{id:1,qty:2},{id:1,qty:1}]});await f.ctx.updateOrderStatus('x','delivery');assert.equal(f.db.products[0].stock,2);await f.ctx.updateOrderStatus('x','delivered');assert.equal(f.db.products[0].stock,2);await f.ctx.updateOrderStatus('x','cancelled');assert.equal(f.db.products[0].stock,5)});
